// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQh8hTYX33FAyaxThSrmJ90bwnqVB6svU',
    appId: '1:1046062558643:web:3e251ca6c315ba14152fc6',
    messagingSenderId: '1046062558643',
    projectId: 'weather-6f036',
    authDomain: 'weather-6f036.firebaseapp.com',
    storageBucket: 'weather-6f036.appspot.com',
    measurementId: 'G-NVDY6MRMCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQzgjV39HV9QEwGD4eIEr5dA8vTEjT5j8',
    appId: '1:1046062558643:android:334d68c5ff0fff5f152fc6',
    messagingSenderId: '1046062558643',
    projectId: 'weather-6f036',
    storageBucket: 'weather-6f036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAno1cBbgiC6z6CpvesrxLa-YbncA0cGtg',
    appId: '1:1046062558643:ios:b49bdbd77fa4e503152fc6',
    messagingSenderId: '1046062558643',
    projectId: 'weather-6f036',
    storageBucket: 'weather-6f036.appspot.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAno1cBbgiC6z6CpvesrxLa-YbncA0cGtg',
    appId: '1:1046062558643:ios:f2ebbcd973534d50152fc6',
    messagingSenderId: '1046062558643',
    projectId: 'weather-6f036',
    storageBucket: 'weather-6f036.appspot.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
